// The app (UI-3). Three decisions the roadmap left open, taken here with
// their reasons, because each one is a claim this project would then have to
// keep:
//
// 1. Form — a progressive web app on the page that already exists, not a
//    native build. The roadmap's own rule is that there is one read path and
//    no second source of truth; a native app is a second implementation of
//    every view, and it would drift the first time a field is added. This way
//    'install' costs one manifest and one service worker, and what is
//    installed is the surface that is already tested.
//
// 2. Reach — loopback, exactly as before. A relay would put approvals on
//    somebody else's machine and break the sentence this surface is built on
//    ('bound to 127.0.0.1'). 'etnpilot ui --host' already serves a tablet on
//    the same network and says plainly what that costs; the app adds nothing
//    to it and no relay is built.
//
// 3. Identity — the token identifies whoever holds it, not a person, and
//    installing the page does not change that. So the app asks for a name,
//    keeps it on the device, and sends it with every decision, where it is
//    recorded as the self-asserted thing it is. A receipt that said 'signed
//    in as' would be claiming an authentication nobody performed.
//
// Offline: the shell is cached, the data never is. A review surface that
// showed yesterday's approvals to somebody deciding today would be worse
// offline than absent, so a navigation without a network says so.

export function renderManifest({ project = "" } = {}) {
  return {
    name: project ? `ETNPilot — ${project}` : "ETNPilot Review",
    short_name: "ETNPilot",
    description: "Approvals, runs and receipts for this project, on the machine that runs it.",
    // The page is the whole app; the token travels in the URL that was
    // installed, which is why the scope is the origin and not '/?token=…'.
    start_url: ".",
    scope: "/",
    display: "standalone",
    orientation: "any",
    background_color: "#0e1513",
    theme_color: "#0e1513",
    icons: [
      { src: "/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
      { src: "/icon-maskable.svg", sizes: "any", type: "image/svg+xml", purpose: "maskable" },
    ],
  };
}

// Drawn rather than fetched: this page loads nothing from a network, and that
// has to hold for the thing sitting on a home screen too.
export function renderIcon({ maskable = false } = {}) {
  // A maskable icon has to survive being cropped to a circle, so the mark sits
  // inside the 40% safe area with the background bleeding to the edges.
  const scale = maskable ? 0.52 : 0.74;
  const offset = (1 - scale) / 2 * 512;
  const size = scale * 512;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <rect width="512" height="512" ${maskable ? "" : 'rx="96" '}fill="#0e1513"/>
  <g transform="translate(${offset.toFixed(1)} ${offset.toFixed(1)}) scale(${(size / 512).toFixed(4)})">
    <path d="M96 96h320v72H176v80h216v72H176v40h248v72H96z" fill="#66d9c4"/>
  </g>
</svg>
`;
}

// The service worker. It caches the shell — the icons and itself — and never
// a response from '/api/' or a navigation, because both carry evidence that is
// only true at the moment it was read.
export function renderServiceWorker(version) {
  return `// Generated by ETNPilot. Shell only: no evidence is ever cached.
const CACHE = "etnpilot-shell-${version}";
const SHELL = ["/icon.svg", "/icon-maskable.svg"];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(caches.keys()
    .then((names) => Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name))))
    .then(() => self.clients.claim()));
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  // Approvals, runs, settings: never from a cache. Stale evidence shown to
  // somebody deciding now is worse than no answer at all.
  if (url.pathname.startsWith("/api/")) return;
  if (event.request.mode === "navigate") {
    event.respondWith(fetch(event.request).catch(() => new Response(
      OFFLINE,
      { status: 503, headers: { "content-type": "text/html; charset=utf-8" } },
    )));
    return;
  }
  if (!SHELL.includes(url.pathname)) return;
  event.respondWith(caches.match(event.request).then((hit) => hit ?? fetch(event.request)));
});

const OFFLINE = ${JSON.stringify(offlinePage())};
`;
}

function offlinePage() {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ETNPilot — no connection</title>
<style>
  :root { color-scheme: light dark; }
  body {
    margin: 0; min-height: 100vh; display: grid; place-content: center; gap: 12px; padding: 24px;
    background: #0e1513; color: #dee4e1;
    font: 400 16px/24px ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  }
  h1 { margin: 0; font: 400 24px/32px inherit; }
  p { margin: 0; max-width: 40ch; color: #bfc9c6; }
</style>
</head><body>
<h1>No connection to this project</h1>
<p>ETNPilot's review surface is served by the machine the project is on, over loopback.
It shows approvals and receipts as they are now, so it never keeps a copy to show while
that machine is out of reach. Reconnect and reload.</p>
</body></html>
`;
}
