import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const DEFAULT_CONFIG = `version: 1
defaultProvider: github-copilot
providers:
  github-copilot:
    type: github-copilot
    model: auto
routing:
  defaults: [github-copilot]
  fallback:
    enabled: true
    maxAttempts: 2
  rules: []
git:
  host: gitlab
  baseUrl: https://gitlab.metropol-it.at
  remote: gitlab
  targetBranch: main
  webhook:
    path: /webhooks/gitlab
    host: 127.0.0.1
    port: 8787
    maxBodyBytes: 1048576
    timestampToleranceSeconds: 300
  issueTrigger:
    enabled: false
    labels: [etnpilot]
    actions: [open, reopen]
    allowConfidential: false
    publish: false
    syncStatus: true
    comment: false
queue:
  database: .etnpilot/state/workflows.sqlite
  pollIntervalMs: 500
  leaseMs: 30000
  retryDelayMs: 5000
  maxAttempts: 1
secrets:
  providers:
    env:
      type: env
      allow:
        - ETNPILOT_GITLAB_TOKEN
        - ETNPILOT_GITLAB_WEBHOOK_SIGNING_SECRET
        - ETNPILOT_GITLAB_WEBHOOK_TOKEN
        - ETNPILOT_GITHUB_TOKEN
        - ETNPILOT_PROVIDER_API_KEY
        - ETNPILOT_OTLP_HEADERS
    local:
      type: file
      root: .etnpilot/secrets
      requireOwnerOnly: true
  values:
    gitlab.apiToken: { provider: env, key: ETNPILOT_GITLAB_TOKEN }
    gitlab.webhookSigningSecret: { provider: env, key: ETNPILOT_GITLAB_WEBHOOK_SIGNING_SECRET }
    gitlab.webhookToken: { provider: env, key: ETNPILOT_GITLAB_WEBHOOK_TOKEN }
    github.token: { provider: env, key: ETNPILOT_GITHUB_TOKEN }
    provider.apiKey: { provider: env, key: ETNPILOT_PROVIDER_API_KEY }
    observability.otlpHeaders: { provider: env, key: ETNPILOT_OTLP_HEADERS }
receipts:
  signing:
    enabled: false
    privateKeyFile: .etnpilot/keys/receipt-signing-private.pem
    publicKeyFile: .etnpilot/receipt-signing-public.pem
codegraph:
  database: .etnpilot/state/codegraph.sqlite
  autoIndex: true
  maxImpactDepth: 20
observability:
  enabled: true
  file: .etnpilot/state/telemetry.jsonl
  serviceName: etnpilot
  environment: development
  failureMode: ignore
  otlp:
    enabled: false
    endpoint: http://127.0.0.1:4318/v1/traces
    headersSecret: observability.otlpHeaders
    timeoutMs: 5000
  pricing:
    currency: USD
    models: {}
  budgets: {}
approval:
  allow: [read]
  requireHuman: [write, shell, network]
  inbox:
    enabled: true
    database: .etnpilot/state/approvals.sqlite
    timeoutMs: 86400000
    pollIntervalMs: 500
policy:
  operations:
    default: deny
    rules:
      - id: protect-credentials
        effect: deny
        kinds: [read, write]
        paths: [.env, .env.*, "**/.env", "**/.env.*", .npmrc, "**/.npmrc", .netrc, "**/.netrc", "**/*.pem", "**/*.key", "**/*.p12", "**/*.pfx", "**/id_rsa", "**/id_ed25519", .git, .git/**, .etnpilot/keys, .etnpilot/keys/**, .etnpilot/secrets, .etnpilot/secrets/**]
      - id: read-project
        effect: allow
        kinds: [read]
        paths: ["**"]
      - id: write-project
        effect: human
        kinds: [write]
        paths: ["**"]
      - id: shell-with-review
        effect: human
        kinds: [shell]
      - id: approved-network-targets
        effect: human
        kinds: [network]
        hosts: [gitlab.metropol-it.at, github.com, api.github.com]
  providers:
    default: deny
    rules:
      - id: configured-copilot
        effect: allow
        providers: [github-copilot]
workspace:
  mode: worktree
  cleanup: never
pluginIsolation:
  setupTimeoutMs: 10000
  callTimeoutMs: 30000
  shutdownTimeoutMs: 1000
  memoryMb: 128
  maxOutputBytes: 65536
  maxMessageBytes: 1048576
  maxPendingRequests: 32
  memoryPollIntervalMs: 100
plugins: []
workflow:
  concurrency: 1
  failFast: true
  timeoutMs: 1800000
  maxSteps: 50
`;

const DEFAULT_IGNORE = `# Generated by ETNPilot. Run state and worktrees are never committed.
state/
worktrees/
keys/
secrets/
*.sqlite
*.sqlite-shm
*.sqlite-wal
`;

export async function initializeProject(root) {
  const configDir = join(root, ".etnpilot");
  await Promise.all([
    mkdir(join(configDir, "agents"), { recursive: true }),
    mkdir(join(configDir, "instructions"), { recursive: true }),
    mkdir(join(configDir, "plugins"), { recursive: true }),
    mkdir(join(configDir, "prompts"), { recursive: true }),
    mkdir(join(configDir, "skills"), { recursive: true }),
    mkdir(join(configDir, "state"), { recursive: true }),
    mkdir(join(configDir, "worktrees"), { recursive: true }),
  ]);
  await Promise.all([
    writeIfAbsent(join(configDir, "etnpilot.yaml"), DEFAULT_CONFIG),
    writeIfAbsent(join(configDir, ".gitignore"), DEFAULT_IGNORE),
  ]);
  return { root, configDir };
}

async function writeIfAbsent(path, content) {
  await writeFile(path, content, { encoding: "utf8", flag: "wx" }).catch((error) => {
    if (error.code !== "EEXIST") throw error;
  });
}
