import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const DEFAULT_CONFIG = `version: 1
defaultProvider: github-copilot
providers:
  github-copilot:
    type: github-copilot
    model: auto
routing:
  defaults: [github-copilot]
  fallback:
    enabled: true
    maxAttempts: 2
  rules: []
git:
  host: gitlab
  baseUrl: https://gitlab.metropol-it.at
  remote: gitlab
  targetBranch: main
codegraph:
  database: .etnpilot/state/codegraph.sqlite
  autoIndex: true
  maxImpactDepth: 20
approval:
  allow: [read]
  requireHuman: [write, shell, network]
workspace:
  mode: worktree
  cleanup: never
workflow:
  concurrency: 1
  failFast: true
  timeoutMs: 1800000
  maxSteps: 50
`;

const DEFAULT_IGNORE = `# Generated by ETNPilot. Run state and worktrees are never committed.
state/
worktrees/
*.sqlite
*.sqlite-shm
*.sqlite-wal
`;

export async function initializeProject(root) {
  const configDir = join(root, ".etnpilot");
  await Promise.all([
    mkdir(join(configDir, "agents"), { recursive: true }),
    mkdir(join(configDir, "instructions"), { recursive: true }),
    mkdir(join(configDir, "plugins"), { recursive: true }),
    mkdir(join(configDir, "prompts"), { recursive: true }),
    mkdir(join(configDir, "skills"), { recursive: true }),
    mkdir(join(configDir, "state"), { recursive: true }),
    mkdir(join(configDir, "worktrees"), { recursive: true }),
  ]);
  await Promise.all([
    writeIfAbsent(join(configDir, "etnpilot.yaml"), DEFAULT_CONFIG),
    writeIfAbsent(join(configDir, ".gitignore"), DEFAULT_IGNORE),
  ]);
  return { root, configDir };
}

async function writeIfAbsent(path, content) {
  await writeFile(path, content, { encoding: "utf8", flag: "wx" }).catch((error) => {
    if (error.code !== "EEXIST") throw error;
  });
}
