import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const DEFAULT_CONFIG = `version: 1
defaultProvider: github-copilot
providers:
  github-copilot:
    type: github-copilot
    model: auto
routing:
  defaults: [github-copilot]
  fallback:
    enabled: true
    maxAttempts: 2
  rules: []
git:
  host: gitlab
  # Replace with your GitLab instance and project before publishing.
  baseUrl: https://gitlab.example.com
  remote: gitlab
  targetBranch: main
  committer:
    name: ETNPilot
    email: etnpilot@localhost
  webhook:
    path: /webhooks/gitlab
    host: 127.0.0.1
    port: 8787
    maxBodyBytes: 1048576
    timestampToleranceSeconds: 300
  issueTrigger:
    enabled: false
    labels: [etnpilot]
    actions: [open, reopen]
    # Required once enabled: only these GitLab users may start a run.
    allowedUsers: []
    fetchBeforeRun: true
    allowConfidential: false
    publish: false
    syncStatus: true
    comment: false
queue:
  database: .etnpilot/state/workflows.sqlite
  pollIntervalMs: 500
  leaseMs: 30000
  retryDelayMs: 5000
  maxAttempts: 1
secrets:
  providers:
    env:
      type: env
      allow:
        - ETNPILOT_GITLAB_TOKEN
        - ETNPILOT_GITLAB_WEBHOOK_SIGNING_SECRET
        - ETNPILOT_GITLAB_WEBHOOK_TOKEN
        - ETNPILOT_GITHUB_TOKEN
        - ETNPILOT_PROVIDER_API_KEY
        - ETNPILOT_OTLP_HEADERS
    local:
      type: file
      root: .etnpilot/secrets
      requireOwnerOnly: true
  values:
    gitlab.apiToken: { provider: env, key: ETNPILOT_GITLAB_TOKEN }
    gitlab.webhookSigningSecret: { provider: env, key: ETNPILOT_GITLAB_WEBHOOK_SIGNING_SECRET }
    gitlab.webhookToken: { provider: env, key: ETNPILOT_GITLAB_WEBHOOK_TOKEN }
    github.token: { provider: env, key: ETNPILOT_GITHUB_TOKEN }
    provider.apiKey: { provider: env, key: ETNPILOT_PROVIDER_API_KEY }
    observability.otlpHeaders: { provider: env, key: ETNPILOT_OTLP_HEADERS }
receipts:
  signing:
    enabled: false
    privateKeyFile: .etnpilot/keys/receipt-signing-private.pem
    publicKeyFile: .etnpilot/receipt-signing-public.pem
codegraph:
  enabled: true
  autoIndex: true
  maxImpactDepth: 20
  startupTimeoutMs: 30000
  tools: [codegraph_explore]
content:
  provenance:
    mode: enforce
    lockFile: .etnpilot/content-lock.json
    verifyAfterRun: true
    maxEntries: 1000
    maxFileBytes: 1048576
observability:
  enabled: true
  file: .etnpilot/state/telemetry.jsonl
  serviceName: etnpilot
  environment: development
  failureMode: ignore
  otlp:
    enabled: false
    endpoint: http://127.0.0.1:4318/v1/traces
    headersSecret: observability.otlpHeaders
    timeoutMs: 5000
  pricing:
    currency: USD
    models: {}
  budgets: {}
approval:
  allow: [read]
  requireHuman: [write, shell, network]
  inbox:
    enabled: true
    database: .etnpilot/state/approvals.sqlite
    timeoutMs: 86400000
    pollIntervalMs: 500
    # Reviewers see the full command by default. Enable to mask
    # credential-looking text at the cost of showing less than was requested.
    redactSecrets: false
policy:
  operations:
    default: deny
    rules:
      - id: protect-credentials
        effect: deny
        kinds: [read, write]
        paths: [.env, .env.*, "**/.env", "**/.env.*", .npmrc, "**/.npmrc", .netrc, "**/.netrc", "**/*.pem", "**/*.key", "**/*.p12", "**/*.pfx", "**/id_rsa", "**/id_ed25519", .git, .git/**, .etnpilot/keys, .etnpilot/keys/**, .etnpilot/secrets, .etnpilot/secrets/**]
      - id: protect-etnpilot-governance
        effect: deny
        kinds: [write]
        paths: [.etnpilot, .etnpilot/**, .gitlab-ci.yml, .github/workflows/**, .git/hooks/**]
      - id: read-project
        effect: allow
        kinds: [read]
        paths: ["**"]
      - id: write-project
        effect: human
        kinds: [write]
        paths: ["**"]
      - id: shell-with-review
        effect: human
        kinds: [shell]
      - id: approved-network-targets
        effect: human
        kinds: [network]
        hosts: [gitlab.example.com, github.com, api.github.com]
  providers:
    default: deny
    rules:
      - id: configured-copilot
        effect: allow
        providers: [github-copilot]
checks:
  # Checks run agent-authored code. They inherit only these variables, so
  # repository and provider credentials stay out of their environment.
  envAllow: []
workspace:
  mode: worktree
  cleanup: never
pluginIsolation:
  setupTimeoutMs: 10000
  callTimeoutMs: 30000
  shutdownTimeoutMs: 1000
  memoryMb: 128
  maxOutputBytes: 65536
  maxMessageBytes: 1048576
  maxPendingRequests: 32
  memoryPollIntervalMs: 100
plugins: []
workflow:
  concurrency: 1
  failFast: true
  timeoutMs: 1800000
  maxSteps: 50
`;

const DEFAULT_IGNORE = `# Generated by ETNPilot. Run state and worktrees are never committed.
state/
worktrees/
keys/
secrets/
*.sqlite
*.sqlite-shm
*.sqlite-wal
`;

const STARTER_AGENT = `name: orchestrator
provider: github-copilot
model: auto
promptRef: orchestrator
skills: []
requires: [chat]
subagents: []
`;

const STARTER_PROMPT = `You implement one requested change at a time in the current repository.

Read before you write, keep the change minimal and reviewable, and run the
project's own checks. Every write, shell command, and network call is reviewed
by a human, so explain what you intend to do and why. Report what you verified
and what remains uncertain; never claim a check passed that you did not run.
`;

export async function initializeProject(root) {
  const configDir = join(root, ".etnpilot");
  await Promise.all([
    mkdir(join(configDir, "agents"), { recursive: true }),
    mkdir(join(configDir, "instructions"), { recursive: true }),
    mkdir(join(configDir, "plugins"), { recursive: true }),
    mkdir(join(configDir, "prompts"), { recursive: true }),
    mkdir(join(configDir, "skills"), { recursive: true }),
    mkdir(join(configDir, "state"), { recursive: true }),
    mkdir(join(configDir, "worktrees"), { recursive: true }),
  ]);
  await Promise.all([
    writeIfAbsent(join(configDir, "etnpilot.yaml"), DEFAULT_CONFIG),
    writeIfAbsent(join(configDir, ".gitignore"), DEFAULT_IGNORE),
    // A runnable starting point: without an agent manifest the first run has
    // nothing to execute.
    writeIfAbsent(join(configDir, "agents", "orchestrator.yaml"), STARTER_AGENT),
    writeIfAbsent(join(configDir, "prompts", "orchestrator.md"), STARTER_PROMPT),
  ]);
  return { root, configDir };
}

async function writeIfAbsent(path, content) {
  await writeFile(path, content, { encoding: "utf8", flag: "wx" }).catch((error) => {
    if (error.code !== "EEXIST") throw error;
  });
}
